### ISSUE TITLE
Release 2.1.0

### ISSUE THREAD

**Issue by olibye** [jimbethancourt/dtangler#9]
Do you have permission to this to maven central?
If not can you release it under a new artifactId?

The original owners appear to have abandoned it.

**Comment by jimbethancourt** [comment]
Hi @olibye!
I'm trying to figure out how to upload to Maven.org per https://maven.apache.org/guides/mini/guide-central-repository-upload.html :-)  It's my first time doing this so I have to get the coordinates updated, update the parent POM with the appropriate info, generate all of the appropriate jars, PGP sign them, and figure out how to get them onto OSSRH. 

I run the Houston Java Users Group and have control over hjug.org and at least another HJUG member is interested in getting involved, so I'm thinking it will make the most sense to use that domain for the top-level group ID.

You can clone the repo and do a **mvn clean install** and run the jar in the dtangler-swingui if you'd like to use the tool in its current state.  You can also clone the dsm-maven-plugin and update the version of dtangler in it and then install that plugin too and use it in your projects.

Best regards,
Jim

**Comment by michalre** [comment]
Thanks for keeping dtangler alive. Looking forward for the release.

**Comment by olibye** [comment]
Almost there. If you need any help, I'm a maintainer of jmock so I know the sonotype deployment pain you're going through!

**Comment by jimbethancourt** [comment]
Thanks @olibye!
I've been granted permission to use the hjug.org domain for my group id by the folks at Sonatype, I've generated and propagated my key, and I can log into the oss.sonatype.org staging repository as well.

It looks like I will need to take a few small additional steps to deploy the artifacts, but that's about it.

My biggest question is whether or not I should keep the package structure intact as org.dtangler (since it has been released previously) or move everything into the org.hjug.dtangler package.  I'm leaning towards repackaging it to keep things clean and since it probably won't take long.


Thanks,
Jim

**Comment by jimbethancourt** [comment]
Hi @olibye and @michalre,
Good news!  It looks like I have released dtangler!  It has been published to the Releases repository and appears on https://oss.sonatype.org/content/repositories/releases/org/hjug/dtangler/.

It should show up on maven.org fairly soon.

You can download the jar-with-dependencies from https://oss.sonatype.org/content/repositories/releases/org/hjug/dtangler/swingui/dtangler-swingui/2.1.0/ and go to town.

Cheers,
Jim

**Comment by jimbethancourt** [comment]
Yup!  It's released now :-)
